# Git
github-url: https://github.com/Prasad459/concourse-cicd
username: prasad459
access-token: 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


# Docker
docker-hub-email: veginatiprasad@gmail.com
docker-hub-username: prasad459
docker-hub-password: Madurai@459
docker-hub-repo-name: prasad459/concourse

#  Kubernetes
server: <<API SERVER URI>>
namespace: <<NAMESPACE>>
cad: <<CERT AUTH DATA>>
token: <<K8s TOKEN>>
